version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore/nuget(deps):"
      prefix-development: "chore/nuget(deps-dev):"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci/actions(deps):"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore/docker(deps):"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore/pip(deps):"
      include: "scope"
