namespace BizPik.Orders.Hub.Modules.Common.Orders.Adapter.Dtos.Enums;

public enum OrderEventType
{
    CREATED = 1,
    CONFIRMED = 2,
    DISPATCHED = 3,
    READY_FOR_PICKUP = 4,
    PICKUP_AREA_ASSIGNED = 5,
    DELIVERED = 6,
    CONCLUDED = 7,
    CANCELLATION_REQUESTED = 8,
    CANCELLATION_REQUEST_DENIED = 9,
    CANCELLED = 10,
    ORDER_CANCELLATION_REQUEST = 11,
    CANCELLED_DENIED = 12,
    CANCELLATION_RESTORE_ITEM = 13,
    CANCELLATION_LOST_ITEM = 14,
    DELIVERYMAN_IN_STORE = 15,
    DELIVERYMAN_CHANGED = 16,
    PREPARATION_REQUESTED = 17,
    PREPARING = 18,
    PICKUP_UP = 19,
}