namespace BizPik.Orders.Hub.Modules.Integrations.Ifood.Domain.ValueObjects.Enums;

public enum IfoodFullOrderStatus
{
    #region ORDER_STATUS
    KEEPALIVE,
    PLACED,
    CONFIRMED,
    SEPARATION_STARTED,
    SEPARATION_ENDED,
    READY_TO_PICKUP,
    DISPATCHED,
    CONCLUDED,
    CANCELLED,
    #endregion

    #region CANCELLATION_REQUEST
    CANCELLATION_REQUESTED,
    CANCELLATION_REQUEST_FAILED,
    CONSUMER_CANCELLATION_REQUESTED,
    CONSUMER_CANCELLATION_ACCEPTED,
    CONSUMER_CANCELLATION_DENIED,
    #endregion

    #region HANDSHAKE_PLATFORM
    HANDSHAKE_DISPUTE,
    HANDSHAKE_SETTLEMENT,
    #endregion

    #region DELIVERY
    ASSIGN_DRIVER,
    GOING_TO_ORIGIN,
    ARRIVED_AT_ORIGIN,
    COLLECTED,
    ARRIVED_AT_DESTINATION,
    DELIVERY_RETURNING_TO_ORIGIN,
    DELIVERY_RETURNED_TO_ORIGIN,
    DELIVERY_CANCELLATION_REQUESTED,
    DELIVERY_DROP_CODE_REQUESTED,
    DELIVERY_DROP_CODE_VALIDATION_SUCCESS,
    DELIVERY_PICKUP_CODE_REQUESTED,
    DELIVERY_PICKUP_CODE_VALIDATION_SUCCESS,
    #endregion

    #region DELIVERY_ADDRESS
    DELIVERY_ADDRESS_CHANGE_REQUESTED,
    DELIVERY_ADDRESS_CHANGE_USER_CONFIRMED,
    DELIVERY_ADDRESS_CHANGE_ACCEPTED,
    DELIVERY_ADDRESS_CHANGE_DENIED,
    #endregion

    #region DELIVERY_GROUP
    DELIVERY_GROUP_ASSIGNED,
    DELIVERY_GROUP_DISMISSED,
    #endregion

    #region DELIVERY_ONDEMAND
    REQUEST_DRIVER,
    REQUEST_DRIVER_SUCCESS,
    REQUEST_DRIVER_FAILED,
    DELIVERY_CANCELLATION_REQUEST_ACCEPTED,
    DELIVERY_CANCELLATION_REQUEST_REJECTED,
    #endregion

    #region DELIVERY_COMPLEMENT
    RETURN_TO_STORE,
    #endregion

    #region ORDER_MODIFIER
    PATCH_REQUESTED,
    PATCH_REQUEST_CANCELLED,
    PATCH_COMMITTED,
    PATCH_COMMITTED_FAILED,
    #endregion

    #region OTHER
    ORDER_PATCHED,
    RECOMMENDED_PREPARATION_START,
    PREPARATION_STARTED,
    CONSUMER_PREPARATION_TIME_REQUESTED,
    CHANGE_PREPARATION_TIME,
    BOX_ASSIGNED,
    #endregion
}